namespace SimonSpells
{
    public static class Words
    {
        // All words have been checked to form valid puzzles.
        public static readonly string[] WordList = "ADMIT|AHEAD|ALIGN|ALIVE|ALLOW|ALONE|ALTAR|ALTER|AMBER|AMONG|APPLE|ARGUE|ATTIC|BAKED|BATCH|BEACH|BEGAN|BENCH|BERRY|BLACK|BLOOM|BREAD|BROWN|BRUSH|BUNCH|BURST|DANCE|DECAY|DELAY|DERBY|DIGIT|DOUBT|DRAIN|DREAM|DUSTY|EAGER|EATEN|ELDER|ENTER|EVADE|EXACT|FAULT|FENCE|FINAL|FLAIR|FLOAT|FLOOD|FOUND|FRESH|FRONT|FUNNY|FUZZY|GENIE|GHOST|GLIDE|GRAMS|GRASP|GROWN|GUESS|HASTE|HINGE|HONOR|HORSE|HOUND|HUMOR|HURRY|IDEAL|IDIOM|IGLOO|IMAGE|IMPLY|IRONY|ISSUE|MAGIC|MAGMA|MANGO|MANOR|MAPLE|MARCH|MATCH|MEDAL|MELON|MERGE|MERRY|METAL|METER|MIGHT|MINOR|MORPH|MOTOR|MOTTO|MOUNT|MOVIE|MUDDY|MUMMY|NACHO|NAILS|NEEDS|NEIGH|NIGHT|NOBLE|NURSE|QUARK|QUEEN|QUERY|QUEST|QUEUE|QUIET|QUIRK|QUITE|QUOTE|RADAR|RADIO|RAISE|RALLY|RANCH|RANGE|RATIO|REACH|READY|RECAP|RELAX|RENEW|REUSE|RHINO|RIGHT|RIGID|RINSE|ROOMY|ROUGH|ROUTE|RUSTY|SAUCE|SCENE|SHARE|SHIFT|SHOCK|SIGHT|SIMON|SINCE|SLEEP|SMART|SMILE|SOILD|SOLAR|SOLVE|SOUTH|SPACE|SPEAK|SPEED|STAFF|STATE|STOOD|STORE|STUDY|SUITE|SUPER|SWEET|SWEPT|SWIFT|SWING|TASTE|TEACH|TENTH|THEIR|THERE|THESE|TODAY|TOPIC|TRADE|TRAIL|TRASH|TRUTH|UDDER|ULTRA|UNDER|UNITE|UNTIL|UPPER|UPSET|VALVE|VAPOR|VAULT|VIGOR|VISIT|VOCAL|WEIGH|WEIRD|WHEEL|WHICH|WHISK|WIDTH|WORSE|WORTH|WROTE".Split('|');
    }
}
